### ISSUE TITLE
when I running train.py

### ISSUE THREAD

**Issue by yifengji** [naoto0804/pytorch-inpainting-with-partial-conv#28]
Traceback (most recent call last):
  File "C:/Users/xxx/Downloads/pytorch-inpainting-with-partial-conv-master/train.py", line 85, in <module>
    num_workers=args.n_threads))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 297, in __init__
    self._put_indices()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 345, in _put_indices
    indices = next(self.sample_iter, None)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\sampler.py", line 138, in __iter__
    for idx in self.sampler:
  File "C:/Users/xxx/Downloads/pytorch-inpainting-with-partial-conv-master/train.py", line 34, in loop
    yield order[i]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by naoto0804** [comment]
Please check if the dataset is successfully loaded at https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/blob/master/train.py#L79. You might specify the wrong path for the dataset root or the mask root

**Comment by yifengji** [comment]
where should I put the right dataset root？and which dataset should I download？


Fengji Yi,   Graduate student
Communication University of China
Neuroscience and Intelligent Media Institute
Email: yifengji1020@163.com


On 1/7/2019 21:18，Naoto Inoue<notifications@github.com> wrote：

Please check if the dataset is successfully loaded at https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/blob/master/train.py#L79. You might specify the wrong path for the dataset root or the mask root

**Comment by naoto0804** [comment]
Please refer to [here](https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/blob/master/README.md#preprocess)
