### ISSUE TITLE
How output all results on the test set in Places2?

### ISSUE THREAD

**Issue by fu123456** [naoto0804/pytorch-inpainting-with-partial-conv#42]
Hi, I have tested test.py file and it does work. Now, I try to test on
all images in Places (in fact, only 50 images for test), and the
evaluation.py file as follows (default 8 -\> len(dataset)):

``` python
import torch
from torchvision.utils import make_grid
from torchvision.utils import save_image

from util.image import unnormalize


def evaluate(model, dataset, device, filename):
    image, mask, gt = zip(*[dataset[i] for i in range(len(dataset)])
    image = torch.stack(image)
    mask = torch.stack(mask)
    gt = torch.stack(gt)
    with torch.no_grad():
        output, _ = model(image.to(device), mask.to(device))
    output = output.to(torch.device('cpu'))
    output_comp = mask * image + (1 - mask) * output
    output_comp = unnormalize(output_comp)
  for j in range(len(dataset):
      each_output_comp = output_comp[j]
      absolut_file_name = os.path.join(save_result_dir, file_name[j])
      save_image(each_output_comp, absolut_file_name)
```

but it outputs errors:

``` text
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    evaluate(model, dataset_val, device, save_result_dir)
  File "/home/user/FG/code/pytorch-inpainting-with-partial-conv/evaluation.py", line 15, in evaluate
    output, _ = model(image.to(device), mask.to(device))
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/FG/code/pytorch-inpainting-with-partial-conv/net.py", line 180, in forward
    h, h_mask = getattr(self, dec_l_key)(h, h_mask)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/FG/code/pytorch-inpainting-with-partial-conv/net.py", line 117, in forward
    h, h_mask = self.conv(input, input_mask)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/FG/code/pytorch-inpainting-with-partial-conv/net.py", line 87, in forward
    output_pre = (output - output_bias) / mask_sum + output_bias
RuntimeError: CUDA out of memory. Tried to allocate 640.00 MiB (GPU 0; 10.73 GiB total capacity; 9.23 GiB already allocated; 399.62 MiB free; 370.56 MiB cached)
```

Please help me. How to solve this such that I can test several thousands
images. Thank you.

**Comment by naoto0804** [comment]
It's out of memory. Don't increase the batchsize. Instead, you can use the network multiple times to iterate through all the data.
