### ISSUE TITLE
索引

### ISSUE THREAD

**Issue by 01SHENyankun** [naoto0804/pytorch-inpainting-with-partial-conv#57]
Traceback (most recent call last):
  File "D:/Code/pytorch-inpainting-with-partial-conv-master/train.py", line 111, in <module>
    image, mask, gt = [x.to(device) for x in next(iterator_train)]
  File "D:\Software Install File\Anaconda3\envs\pconv\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "D:\Software Install File\Anaconda3\envs\pconv\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "D:\Software Install File\Anaconda3\envs\pconv\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Software Install File\Anaconda3\envs\pconv\lib\site-packages\torch\utils\data\dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Code\pytorch-inpainting-with-partial-conv-master\places2.py", line 30, in __getitem__
    gt_img = Image.open(self.paths[index])
TypeError: only integer scalar arrays can be converted to a scalar index

How should this problem be solved？

**Comment by naoto0804** [comment]
Hi.

1. Please make sure to download Places2 dataset and put it to the specified location following [here](https://github.com/naoto0804/pytorch-inpainting-with-partial-conv#preprocess).
2. If 1 does not solve the problem, please print `self.paths` and see if the paths for the image files are listed.

**Comment by 01SHENyankun** [comment]
Thank you for your reply. I use the Paris dataset. I print self However, there is no display, I am deeply confused







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "naoto0804/pytorch-inpainting-with-partial-conv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月16日(星期六) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [naoto0804/pytorch-inpainting-with-partial-conv] 索引 (Issue #57)





 
Hi.
  
Please make sure to download Places2 dataset and put it to the specified location following here.
 
If 1 does not solve the problem, please print self.paths and see if the paths for the image files are listed.
